- path: /urlshort
  url: https://github.com/BolajiOlajide/urlshort
- path: /google
  url: https://google.com
- path: /github
  url: https://github.com/BolajiOlajide
- path: /twitter
  url: https://twitter.com/Bolaji___
- path: /page-load
  url: https://www.codebeast.dev/improve-page-load-performance-with-modern-browser-hints-best-practices/
- path: /hJKD
  url: https://www.linkedin.com/in/bolaji-olajide-95b08777/